version: '3.6'
services:
  site:
    container_name: phalcon-site
    build: site
    restart: always
    ports:
      - 80:80
    volumes:
      - ./site:/var/www/html

  users:
    container_name: phalcon-users
    build: users
    ports:
      - '81'
      - "127.0.0.1:81:80"
    restart: always
    volumes:
      - ./users:/var/www/html




